<a href="https://colab.research.google.com/github/RUMONMD89/Sentiment-Analysis-with-SimpleRNN/blob/main/Sentiment_Analysis_(with_simpleRNN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install keras-preprocessing


  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl.metadata (1.9 kB)
Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)


In [4]:

from keras_preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding



# Sample text data
docs = [
    'hello japan',
    'go japan',
    'japan japan',
    'hip hip hurray',
    'owo sugoi oishii',
    'ganbatte ganbatte',
    'hai ganbarimasu',
    'miyazaki miyazaki',
    'ohtani ohtani',
    'japan long live'
]

In [5]:
# Tokenize the text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)

In [8]:
# Convert texts to sequences and pad them
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[6, 1],
 [7, 1],
 [1, 1],
 [2, 2, 8],
 [9, 10, 11],
 [3, 3],
 [12, 13],
 [4, 4],
 [5, 5],
 [1, 14, 15]]

In [16]:
padded_sequences = pad_sequences(sequences, padding='post')
padded_sequences

array([[ 6,  1,  0],
       [ 7,  1,  0],
       [ 1,  1,  0],
       [ 2,  2,  8],
       [ 9, 10, 11],
       [ 3,  3,  0],
       [12, 13,  0],
       [ 4,  4,  0],
       [ 5,  5,  0],
       [ 1, 14, 15]], dtype=int32)

In [15]:
len(tokenizer.word_index)

15

In [10]:
# Debugging: Print vocabulary size and padded sequences shape
vocab_size = len(tokenizer.word_index) + 1  # Add 1 for padding token
print("Vocabulary size:", vocab_size)
print("Padded sequences shape:", padded_sequences.shape)

Vocabulary size: 16
Padded sequences shape: (10, 3)


In [12]:
# Build the model
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=2))

In [13]:
# Build the model explicitly with sample input shape
model.build(input_shape=(None, padded_sequences.shape[1]))

In [14]:
# Print model summary
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ (None, 3, 2)                │              32 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 32 (128.00 B)

 Trainable params: 32 (128.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.compile('adam','accuracy')

In [40]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [38]:
padded_sequences = pad_sequences(sequences, padding='post')
padded_sequences

array([[ 6,  1,  0],
       [ 7,  1,  0],
       [ 1,  1,  0],
       [ 2,  2,  8],
       [ 9, 10, 11],
       [ 3,  3,  0],
       [12, 13,  0],
       [ 4,  4,  0],
       [ 5,  5,  0],
       [ 1, 14, 15]], dtype=int32)

In [23]:
import numpy as np
# Convert the padded sequences to a NumPy array
padded_sequences = np.array(padded_sequences)

In [25]:
pred = model.predict(padded_sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 263ms/step
[[[-0.02483994 -0.04596784]
  [ 0.03042989 -0.04623133]
  [ 0.00339835  0.0349299 ]]

 [[-0.01407784  0.03266375]
  [ 0.03042989 -0.04623133]
  [ 0.00339835  0.0349299 ]]

 [[ 0.03042989 -0.04623133]
  [ 0.03042989 -0.04623133]
  [ 0.00339835  0.0349299 ]]

 [[-0.01154202  0.02756851]
  [-0.01154202  0.02756851]
  [ 0.01308886 -0.02759316]]

 [[ 0.00634748  0.00478542]
  [ 0.04622329 -0.01419115]
  [ 0.01029891 -0.01271851]]

 [[ 0.01269845  0.00761433]
  [ 0.01269845  0.00761433]
  [ 0.00339835  0.0349299 ]]

 [[-0.00092981  0.03058989]
  [ 0.0233274   0.01218262]
  [ 0.00339835  0.0349299 ]]

 [[-0.03466354 -0.0399575 ]
  [-0.03466354 -0.0399575 ]
  [ 0.00339835  0.0349299 ]]

 [[ 0.03413321 -0.03983857]
  [ 0.03413321 -0.03983857]
  [ 0.00339835  0.0349299 ]]

 [[ 0.03042989 -0.04623133]
  [-0.04928955 -0.00134612]
  [ 0.02777839 -0.01468851]]]


In [30]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences as keras_pad_sequences # Rename the function
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [31]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [32]:
# Use the renamed function for padding
X_train = keras_pad_sequences(X_train,padding='post',maxlen=50)
X_test = keras_pad_sequences(X_test,padding='post',maxlen=50)

In [33]:
X_train.shape

(25000, 50)

In [36]:
from keras.models import Sequential
from keras.layers import Embedding, SimpleRNN, Dense

# Define the model
model = Sequential()

# Add layers
vocab_size = 10000  # Example vocab size
embedding_dim = 2
sequence_length = 50

# Embedding layer
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim))

# SimpleRNN layer
model.add(SimpleRNN(32, return_sequences=False))

# Dense output layer
model.add(Dense(1, activation='sigmoid'))

# Build the model explicitly
model.build(input_shape=(None, sequence_length))

# Print model summary
model.summary()


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)              │ (None, 50, 2)               │          20,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_1 (SimpleRNN)             │ (None, 32)                  │           1,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 13ms/step - acc: 0.5366 - loss: 0.6851 - val_acc: 0.7822 - val_loss: 0.4690
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 17s 9ms/step - acc: 0.8060 - loss: 0.4255 - val_acc: 0.8073 - val_loss: 0.4225
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - acc: 0.8634 - loss: 0.3323 - val_acc: 0.8064 - val_loss: 0.4309
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - acc: 0.8825 - loss: 0.2920 - val_acc: 0.7984 - val_loss: 0.4625
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.8950 - loss: 0.2682 - val_acc: 0.7881 - val_loss: 0.4617
